debug: false
management:
  endpoints:
    web:
      .exposure.inclue: "*"
logging:
  level:
    com.example.fastcampusboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descripter.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fcboard
    username: root
    password: Kamilaezail21!
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_branch_fetch_size: 100
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3.decoupled-logic: true

#---
#
#spring:
#  config:
#    activate:
#      on-cloud-platform: testdb
#  datasource:
#    url: jdbc:h2:mem:fcboard;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none